### ISSUE TITLE
[App Request] DDNS-updater

### ISSUE THREAD

**Issue by MX10-AC2N** [IceWhaleTech/CasaOS-AppStore#119]
### App Information

- Name: < DDNS-Updater >
- Short Description: < Container to update DNS records periodically with WebUI for many DNS providers >

- GitHub Repository: < https://github.com/qdm12/ddns-updater >
- Docker Image: < https://hub.docker.com/r/qmcgaw/ddns-updater/ >

### Why do you want this app?

Before I used ddclient to do this but I had no feedback via webui, this app solves the problem well, update my IP and visual with an ultra simple webui. Really great for CasaOS..!

**Comment by rstuhlmuller** [comment]
Pretty sweet find! I was able to get it up and running manually. I have never contributed with a brand new app, but here is what I attempted to come up with. When I test, I will create a PR. See here: https://github.com/rstuhlmuller/CasaOS-AppStore/tree/main/Apps/DDNS-Updater
