### ISSUE TITLE
[Bug] Can you please upgrade vaultwarden to the latest version?

### ISSUE THREAD

**Issue by SkYNewZ** [IceWhaleTech/CasaOS-AppStore#206]
**Describe the bug**
Bitwarden has change some stuff regarding the user connection. Vaultwarden has implemented these changes on version >= 1.27. Currently provided version is 1.24. Can you upgrade it please ?

**Comment by Kordrad** [comment]
![image](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/29141389/015e9b60-2b8b-401c-bb7c-4ecdfce42a8a)
can you check again?

**Comment by thedroidkid** [comment]
I can also confirm 1.28.1 is showing for me as well

**Comment by tigerinus** [comment]
Closing since it's `1.28.1` now.

PR to bump to newer version is always welcomed.
