### ISSUE TITLE
[Bug] “FileBrowser” PUID/PGID do not take effect

### ISSUE THREAD

**Issue by LSP0123** [IceWhaleTech/CasaOS-AppStore#230]
**Describe the bug**
“FileBrowser” PUID/PGID do not take effect
the file/folder created by FileBrowse is belong to root user

**To Reproduce**
install FileBrowse in Appstore， create a folder in FileBrowser
`ls -al ` check the folder
`drwxr-xr-x 1 root   root     0  7月 31 10:44 test`

**Expected behavior**
the file/folder is belong to 1000:1000
```
casaos@nas:/DATA/AppData$ mkdir Expected-behavior
casaos@nas:/DATA/AppData$ ls -al | grep Expected-behavior
drwxrwxr-x 1 casaos casaos   0  7月 31 10:48 Expected-behavior
```

**Screenshots**
![image](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/31061624/398b0e12-f3df-405a-87a2-1a1cdbc423a1)

**Comment by LinkLeong** [comment]
Sorry to get back to you now, can you tell me what version your casaos is, I mean what version was casaos when you created this app?

**Comment by LSP0123** [comment]
casaos version :  0.4.4
it has the same behavior in 0.4.4-1

> 很抱歉现在回复您，您能告诉我您的 casaos 是什么版本吗，我的意思是您创建此应用程序时 casaos 是什么版本？

**Comment by CorrectRoadH** [comment]
Yes. I can reproduce it 👀 I will try to fix it

**Comment by CorrectRoadH** [comment]
the problem is caused by file browser. It didn't support user mapping. such as linuxserver syncthing. the function is working fine.🫨

**Comment by ETWang1991** [comment]
The CasaOS team is discussing how to solve this problem

**Comment by LSP0123** [comment]
How to solve this Problem:
```
mkdir /DATA/AppData/filebrowser
touch /DATA/AppData/filebrowser/filebrowser.db 
touch /DATA/AppData/filebrowser/settings.json
cat <<'EOF' > /DATA/AppData/filebrowser/settings.json
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
EOF

```
the "volumes" of filebrowser.yaml should be like this:

>     volumes:
>       - type: bind
>         source: /DATA/AppData/filebrowser/settings.json
>         target: /config/settings.json
>       - type: bind
>         source: /DATA
>         target: /srv
>       - type: bind
>         source: /DATA/AppData/filebrowser/filebrowser.db
>         target: /database/filebrowser.db
