### ISSUE TITLE
[App Request] Tailscale

### ISSUE THREAD

**Issue by swarupbhc** [IceWhaleTech/CasaOS-AppStore#244]
### App Information

- Name: Tailscale
- Short Description: Connect your devices and users together in your own secure virtual private network. 
- Official Website: https://tailscale.com
- GitHub Repository: https://github.com/tailscale/tailscale
- Docker Image: https://hub.docker.com/r/tailscale/tailscale

### Why do you want this app?

To Connect to my casa os server from anywhere securely and faster.

**Comment by tigerinus** [comment]
dup #62
