### ISSUE TITLE
[App Request] IMMICH

### ISSUE THREAD

**Issue by swarupbhc** [IceWhaleTech/CasaOS-AppStore#245]
### App Information

- Name: IMMICH
- Short Description: SELF-HOSTED BACKUP SOLUTION FOR PHOTOS AND VIDEOS ON MOBILE DEVICE
- Official Website: https://immich.app
- GitHub Repository: https://github.com/immich-app/immich
- Docker Image: https://documentation.immich.app/docs/install/docker-compose

### Why do you want this app?

Store photos & videos, face grouping, with official app support

**Comment by swarupbhc** [comment]
@tigerinus @thedroidkid @CorrectRoadH @raller1028

**Comment by LonnyX** [comment]
This app is a must-have! I was bummed to see it's not on the App Store, even though it has 20k stars on GitHub

**Comment by CorrectRoadH** [comment]
> This app is a must-have! I was bummed to see it's not on the App Store, even though it has 20k stars on GitHub

I also wanna it🥺 IMMICH is cool!

**Comment by kirtan3d** [comment]
I also want this app in App store.

**Comment by Shamino-UO** [comment]
Yes pleaseeeeeee! Immich to CasaOS!

**Comment by tigerinus** [comment]
dup

- #63 

everyone please move your likes over to #63 

Thanks!

**Comment by chilman408** [comment]
I am a new Casa OS user but I can't seem to find Immich on the Appstore...

**Comment by Cp0204** [comment]
Try this AppStore source:

https://play.cuse.eu.org/Cp0204-AppStore-Play.zip

immich is under active development and may encounter AppStore adaptation issues, please feel free to feedback if you have any questions.

![1000023013](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/5239753/e0bc1451-a1d9-4fec-a781-309afc9dc77e)
