### ISSUE TITLE
[App Request] trilium

### ISSUE THREAD

**Issue by Jerakin** [IceWhaleTech/CasaOS-AppStore#258]
### App Information

- Name: trilium
- Short Description:  A hierarchical note taking application with focus on building large personal knowledge bases
- Official Website: https://github.com/zadam/trilium
- GitHub Repository: https://github.com/zadam/trilium
- Docker Image: zadam/trilium:latest

### Why do you want this app?

One of the most popular possible to self host note taking apps. Can also serve as a little wiki of your own.

### Additional information?

https://github.com/zadam/trilium/wiki/Docker-server-installation

**Comment by kd9lsv** [comment]
@WisdomSky Has already implemented this in the [Coolstore AppStore](https://github.com/WisdomSky/CasaOS-Coolstore)

**Comment by TephlonDude** [comment]
I added it last week to the main appstore
