### ISSUE TITLE
[App Request] Streamio

### ISSUE THREAD

**Issue by Cristiandis** [IceWhaleTech/CasaOS-AppStore#264]
### App Information

- Name: <Streamio>
- Short Description: <Stremio is a modern media center that's a one-stop solution for your video entertainment. You discover, watch and organize video content from easy to install addons.>
- Official Website: <https://www.stremio.com/>
- GitHub Repository: <https://github.com/Stremio/stremio-web>
- Docker Image: <https://hub.docker.com/r/stremio/server>

### Why do you want this app?

As an extra media player and streaming service.

**Comment by yesbhautik** [comment]
![image](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/63995315/58e96cfd-6acd-4ec0-9e8c-efdfa90b570c)
![image](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/63995315/4f60887d-1eb8-47e3-a789-7e2ee5d7f16e)

**Comment by tmsgm** [comment]
waiting on this too

**Comment by k1sta** [comment]
same problem here!
it seems related to HTTPS and HTTP connection, 'cause a while ago Ive bypassed that using http to connect to the port 11470 directly. however, now that doesnt work
