### ISSUE TITLE
[App Request] Portainer BE

### ISSUE THREAD

**Issue by c10000000** [IceWhaleTech/CasaOS-AppStore#265]
### App Information

- Name: Portainer BE
- Short Description: Portainer Business Edition is a fully featured service delivery platform for containerized applications that can be used to manage single and multi-cluster Docker, Swarm, Kubernetes and ACI environments. It is designed to be as simple to deploy as it is to use. The application allows you to manage all your orchestrator resources (containers, images, volumes, networks and more) through a ‘smart’ GUI and/or an extensive API.
- Official Website:  https://www.portainer.io/
- Docker Image: https://hub.docker.com/r/portainer/portainer-ee

### Why do you want this app?

Easier to control dockers, pull logs and more 

### Additional information?

Portainer is already in the App Store but this is Portainer business. It has more functionalities than the normal portainer.

**Comment by tigerinus** [comment]
@c10000000 would portainer ce be sufficient?

See https://github.com/IceWhaleTech/CasaOS-AppStore/pull/212
