### ISSUE TITLE
third-party Appstore 

### ISSUE THREAD

**Issue by arch3rPro** [IceWhaleTech/CasaOS-AppStore#270]
我维护了一个 第三方 应用商店，主要都是一些渗透相关的工具，可以加入到第三方应用商店推荐么？
以下是链接：https://github.com/arch3rPro/Pentest-Docker

**Comment by arch3rPro** [comment]
CasaOS Pentest-Docker AppStore

Pentest-Docker is a CasaOS third-party Appstore with Pentest-Tools apps.

Source link:
https://github.com/arch3rPro/Pentest-Docker/archive/refs/heads/master.zip

**Comment by kd9lsv** [comment]
This probably should be added via PR in the [third party repo](https://github.com/IceWhaleTech/Awesome-CasaOS/blob/main/content/3rd-party-app-stores/list.md)
