### ISSUE TITLE
[Bug] Emby server not installing latest version

### ISSUE THREAD

**Issue by wolf-yuan-6115** [IceWhaleTech/CasaOS-AppStore#29]
**Describe the bug**
emby server in app store is not latest version 

**To Reproduce**

1. Install Emby

**Expected behavior**
Pulls `linuxserver/emby:latest`

**Comment by tigerinus** [comment]
Should be resolved in https://github.com/IceWhaleTech/CasaOS-AppStore/pull/177

Thanks to @WisdomSky

**Comment by Natetronn** [comment]
@tigerinus 

It didn't bump the version that is being used in the App store, as seen in this file here:

https://github.com/IceWhaleTech/CasaOS-AppStore/blob/main/Apps/Emby/appfile.json

The actual line in question, where you can see an old version is still being used, is here: https://github.com/IceWhaleTech/CasaOS-AppStore/blob/main/Apps/Emby/appfile.json#L32C37-L32C37

Looks like `latest` tag was added to Embystat, however.

**Comment by Natetronn** [comment]
https://github.com/IceWhaleTech/CasaOS-AppStore/pull/195

**Comment by tigerinus** [comment]
@Natetronn - please see

- #167
