### ISSUE TITLE
Update Radarr

### ISSUE THREAD

**Issue by rstuhlmuller** [IceWhaleTech/CasaOS-AppStore#344]
Update radarr to latest (5.1.3.8246)

<img width="1440" alt="Screenshot 2023-11-26 at 6 11 45 PM" src="https://github.com/IceWhaleTech/CasaOS-AppStore/assets/57728706/217e8c91-f1d3-4439-88e0-afc9e8e581d2">

**Comment by Dysta** [comment]
Hello, the docker-compose image is already set as `5.1.3`. This mean that if you click on settings then save, it will pull the latest 5.1.3 version from linuxserver

**Comment by Cp0204** [comment]
https://github.com/IceWhaleTech/CasaOS-AppStore/pull/343/commits/66dc23d27b4090b679652f4ccb68d34f9ed9b23d#diff-a8a4d169fbdc6318f1918a47b5fdfe3df58cfe2895e54320c57427f4f40ab391

Has been updated
