### ISSUE TITLE
Issue in stremio App in AppStore [#264]

### ISSUE THREAD

**Issue by yesbhautik** [IceWhaleTech/CasaOS-AppStore#361]
Issue: Server error
Faild to Fetch Video

![image](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/63995315/ce0b72b4-2a36-48e6-a32a-5d0957a0177f)
![image](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/63995315/c0cab50c-2b96-4927-bb4b-d70fde866090)

**Comment by tmsgm** [comment]
i have this too what can i do?
