### ISSUE TITLE
Add NET_ADMIN to pihole

### ISSUE THREAD

**Issue by Hedius** [IceWhaleTech/CasaOS-AppStore#4]
The docker container needs the NET_ADMIN permission to process DHCP requests. Maybe include it by default?
Otherwise, the pihole FTL server fails to start without it if DHCP is enabled.

**Comment by ETWang1991** [comment]
1. 是否需要仅开发者模式下提供这一修改项
2. 修改项是否放在Docker设置里

1. whether the modifier should be available in developer mode only
2. whether the modifications are placed in Docker settings

**Comment by EthraZa** [comment]
Pi-hole does need NET_ADMIN, but it will only work as DHCP server if using network HOST, other wise it needs a DHCP relay container (set as network host) like: [DHCP-Relay](https://github.com/modem7/DHCP-Relay).
