### ISSUE TITLE
[Feedback] Webstore App Incorrect : Gitea warning there is no RPi version

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS-AppStore#47]
### Description

Gitea: Git with a cup of tea
Warning message: Not compatible with armv7 devices.

- This is incorrect. See these links for details.
REF: https://gitea.io/en-us/
         https://codeopolis.com/posts/painlessly-running-a-gitea-docker-container/
         https://hub.docker.com/r/patrickthedev/gitea-rpi

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 14239 
	 - Disk Used: 3912 
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:744M Core:4 Linux rpi2-cups 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Safari 
	 - Version: 16.4.1

**Comment by tigerinus** [comment]
working with @lunny on this one.

**Comment by lunny** [comment]
If you are using RPI 3 or 4, I think you can use arm64 image. For RPI 3 the default OS is 32bit, you need to upgrade to a 64bit OS.

**Comment by rodhammond** [comment]
I'm using an RPi2. Pretty sure 32bit is correct.
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Cp0204** [comment]
[add Gitea-arm](https://github.com/Cp0204/CasaOS-AppStore-Play/commit/1f2c0e8d92b7e02fa913ad5465896380975e3afa)

https://github.com/IceWhaleTech/CasaOS-AppStore/pull/343

[Apps_arm](https://github.com/Cp0204/CasaOS-AppStore-Play/tree/main/Apps_arm) store source link:

```
https://play.cuse.eu.org/Cp0204-AppStore-Play-arm.zip
```
