### ISSUE TITLE
[App Request] Homebridge

### ISSUE THREAD

**Issue by mwwgithub** [IceWhaleTech/CasaOS-AppStore#51]
### App Information

- Name: Homebridge
- Short Description: Homebridge allows you to integrate with smart home devices that do not natively support HomeKit.
- Official Website: https://homebridge.io/
- GitHub Repository: https://github.com/homebridge/homebridge
- Docker Image: https://github.com/oznu/docker-homebridge

**Comment by tigerinus** [comment]
- #332
