### ISSUE TITLE
[App Request] Wireguard-Easy (Update to official)

### ISSUE THREAD

**Issue by rstuhlmuller** [IceWhaleTech/CasaOS-AppStore#525]
### App Information

- Name: WireGuard Easy
- Short Description: A simple web interface to manage WireGuard VPN connections
- Official Website: N/A
- GitHub Repository: https://github.com/wg-easy/wg-easy
- Docker Image: ghcr.io/wg-easy/wg-easy:latest
<img width="1920" alt="Screenshot 2024-07-07 at 6 11 11 PM" src="https://github.com/IceWhaleTech/CasaOS-AppStore/assets/57728706/e065f779-fe75-4e1d-b4e0-c629f1cc1854">

### Why do you want this app?

WireGuard Easy is a valuable tool for simplifying the setup and management of WireGuard VPN connections. It provides a user-friendly web interface that makes it easier for both novice and experienced users to create, configure, and manage WireGuard tunnels. The existing image for this app has been archived as of **April 11, 2024**

**Comment by dragonfire1119** [comment]
This has been added to BigBearCasaOS: https://community.bigbeartechworld.com/t/added-wg-easy-to-bigbearcasaos/1631?u=dragonfire1119

**Comment by rstuhlmuller** [comment]
> This has been added to BigBearCasaOS: https://community.bigbeartechworld.com/t/added-wg-easy-to-bigbearcasaos/1631?u=dragonfire1119

It is already on the official apps, just not the official version of wireguard easy.
