### ISSUE TITLE
[App Request] Glances

### ISSUE THREAD

**Issue by joaobosconff** [IceWhaleTech/CasaOS-AppStore#568]
### App Information

- Name:  Glances
- Short Description: System Monitor
- GitHub Repository: https://github.com/nicolargo/glances
- Docker Image: https://hub.docker.com/r/nicolargo/glances

### Why do you want this app?

Good app to show all server resource statistics

**Comment by joaobosconff** [comment]
working on it

**Comment by dragonfire1119** [comment]
This has been added to BigBearCasaOS: https://community.bigbeartechworld.com/t/how-to-install-glances-on-casaos-using-bigbearcasaos/244?u=dragonfire1119
