### ISSUE TITLE
[App Request] Plex (but the server version)

### ISSUE THREAD

**Issue by Gladosator** [IceWhaleTech/CasaOS-AppStore#72]
### App Information

- Name: Plex Server
- Short Description: A home for all your media and compatible with the Plex app on every platform
- Official Website: https://www.plex.tv/
- GitHub Repository: https://github.com/plexinc/pms-docker
- Docker Image: plexinc/pms-docker

### Why do you want this app?

Because it' dumb to only have the Normal app without the Server functionality since CasaOS is supposed to be for a home **server** and also the server app has all of the normal apps functionality.

**Comment by realNotsneaky** [comment]
@tigerinus i am having the same issue. I am moving my server from Windows to casaos. I followed the instructions but cant seem to claim it as a server. any guidance would be great! 
![image](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/140869057/3f3e5552-c953-4612-83b9-47d4b8fd7010)


Thanks!

**Comment by fleshcrucifix** [comment]
> I think what you may actually be missing is the Plex Claim token. You need to go to https://www.plex.tv/claim/ and generate a claim token. Then copy that token and set it as a PLEX_CLAIM environment variable in your container.

Every time I have to start from scratch I forget to do this and spend hours frustrated....  So simple, but so easy to forget!!!  Thanks!!!
