### ISSUE TITLE
[App Request] Resilio Sync

### ISSUE THREAD

**Issue by OhEhmGeh** [IceWhaleTech/CasaOS-AppStore#80]
### App Information

- Name: Resilio Sync
- Short Description: Sync uses peer-to-peer technology to provide fast, private file sharing for teams and individuals.
- Official Website: https://www.resilio.com/
- GitHub Repository: https://github.com/bt-sync/sync-docker
- Docker Image: resilio/sync

### Why do you want this app?

Syncing backups between multiple systems.

**Comment by tigerinus** [comment]
added in https://github.com/IceWhaleTech/CasaOS-AppStore/releases/tag/v0.4.4-alpha9
